import os

os.environ["DAM_SERVER_ADDRESS"] = "http://ip_or_domain_name"
os.environ["DAM_ACCOUNT_KEY"] = "c531XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
os.environ["AWS_ACCESS_KEY_ID"] = "AKXXXXXXXXXXXXXXXXXX"
os.environ["AWS_SECRET_ACCESS_KEY"] = "OXhXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
os.environ["AWS_DEFAULT_REGION"] = "us-west-2"
